// <auto-generated />
using System;
using AngularApp3.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularApp3.Server.Migrations
{
    [DbContext(typeof(AgenciaContext))]
    [Migration("20260710025058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AngularApp3.Server.Models.Campana", b =>
                {
                    b.Property<int>("CampanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("CampanaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Campanas");

                    b.HasData(
                        new
                        {
                            CampanaId = 1,
                            ClienteId = 1,
                            FechaInicio = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sabor de temporada",
                            Presupuesto = 8500m
                        },
                        new
                        {
                            CampanaId = 2,
                            ClienteId = 2,
                            FechaInicio = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Corre Ecuador",
                            Presupuesto = 15000m
                        },
                        new
                        {
                            CampanaId = 3,
                            ClienteId = 3,
                            FechaInicio = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Chequeo a tiempo",
                            Presupuesto = 12000m
                        },
                        new
                        {
                            CampanaId = 4,
                            ClienteId = 4,
                            FechaInicio = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Hogar sostenible",
                            Presupuesto = 9750m
                        });
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Contacto = "Ana Torres",
                            Email = "ana@cafecentral.com",
                            NombreEmpresa = "Café Central",
                            Telefono = "0991234567"
                        },
                        new
                        {
                            ClienteId = 2,
                            Contacto = "Luis Mora",
                            Email = "luis@deportesandinos.com",
                            NombreEmpresa = "Deportes Andinos",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            ClienteId = 3,
                            Contacto = "María López",
                            Email = "maria@clinicavida.com",
                            NombreEmpresa = "Clínica Vida",
                            Telefono = "0974455667"
                        },
                        new
                        {
                            ClienteId = 4,
                            Contacto = "Carlos Ruiz",
                            Email = "carlos@ecohogar.com",
                            NombreEmpresa = "EcoHogar",
                            Telefono = "0961122334"
                        });
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Disenador", b =>
                {
                    b.Property<int>("DisenadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("DisenadorId");

                    b.ToTable("Disenadores");

                    b.HasData(
                        new
                        {
                            DisenadorId = 1,
                            Email = "sofia@agencia.com",
                            Especialidad = "Diseño gráfico",
                            Nombre = "Sofía Vega",
                            Telefono = "0995551100"
                        },
                        new
                        {
                            DisenadorId = 2,
                            Email = "mateo@agencia.com",
                            Especialidad = "Diseño web",
                            Nombre = "Mateo Paz",
                            Telefono = "0985552200"
                        },
                        new
                        {
                            DisenadorId = 3,
                            Email = "valentina@agencia.com",
                            Especialidad = "Ilustración",
                            Nombre = "Valentina Cruz",
                            Telefono = "0975553300"
                        },
                        new
                        {
                            DisenadorId = 4,
                            Email = "diego@agencia.com",
                            Especialidad = "Contenido audiovisual",
                            Nombre = "Diego León",
                            Telefono = "0965554400"
                        });
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Entregable", b =>
                {
                    b.Property<int>("EntregableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisenadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("EntregableId");

                    b.HasIndex("CampanaId");

                    b.HasIndex("DisenadorId");

                    b.ToTable("Entregables");

                    b.HasData(
                        new
                        {
                            EntregableId = 1,
                            CampanaId = 1,
                            DisenadorId = 1,
                            FechaEntrega = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Identidad visual"
                        },
                        new
                        {
                            EntregableId = 2,
                            CampanaId = 1,
                            DisenadorId = 3,
                            FechaEntrega = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Publicaciones para redes"
                        },
                        new
                        {
                            EntregableId = 3,
                            CampanaId = 2,
                            DisenadorId = 4,
                            FechaEntrega = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Video promocional"
                        },
                        new
                        {
                            EntregableId = 4,
                            CampanaId = 3,
                            DisenadorId = 2,
                            FechaEntrega = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Página de campaña"
                        },
                        new
                        {
                            EntregableId = 5,
                            CampanaId = 4,
                            DisenadorId = 1,
                            FechaEntrega = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Catálogo digital"
                        },
                        new
                        {
                            EntregableId = 6,
                            CampanaId = 2,
                            DisenadorId = 3,
                            FechaEntrega = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tipo = "Afiches"
                        });
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Campana", b =>
                {
                    b.HasOne("AngularApp3.Server.Models.Cliente", "Cliente")
                        .WithMany("Campanas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Entregable", b =>
                {
                    b.HasOne("AngularApp3.Server.Models.Campana", "Campana")
                        .WithMany("Entregables")
                        .HasForeignKey("CampanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AngularApp3.Server.Models.Disenador", "Disenador")
                        .WithMany("Entregables")
                        .HasForeignKey("DisenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campana");

                    b.Navigation("Disenador");
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Campana", b =>
                {
                    b.Navigation("Entregables");
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Cliente", b =>
                {
                    b.Navigation("Campanas");
                });

            modelBuilder.Entity("AngularApp3.Server.Models.Disenador", b =>
                {
                    b.Navigation("Entregables");
                });
#pragma warning restore 612, 618
        }
    }
}
